"""crate tables again

Revision ID: 50205d691e94
Revises: 
Create Date: 2024-09-17 22:56:51.222421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50205d691e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('order_placed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('written_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('customer')
    # ### end Alembic commands ###
